"""Initial migration

Revision ID: d079c3fe7e8b
Revises: 
Create Date: 2026-07-13 11:46:37.451270

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd079c3fe7e8b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('slug', sa.String(length=255), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('parent_id', sa.BigInteger(), nullable=True),
    sa.Column('sort_order', sa.BigInteger(), nullable=True),
    sa.Column('icon', sa.String(length=255), nullable=True),
    sa.Column('color', sa.String(length=255), nullable=True),
    sa.Column('is_visible', sa.Boolean(), nullable=True),
    sa.Column('articles_count', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.create_index('idx_categories_is_visible', ['is_visible'], unique=False)
        batch_op.create_index('idx_categories_parent', ['parent_id'], unique=False)
        batch_op.create_index('idx_categories_slug', ['slug'], unique=True)
        batch_op.create_index('idx_categories_sort_order', ['sort_order'], unique=False)

    op.create_table('email_service_configs',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('site_id', sa.Integer(), nullable=True),
    sa.Column('from_email', sa.String(length=255), nullable=False),
    sa.Column('from_name', sa.String(length=255), nullable=True),
    sa.Column('api_key', sa.Text(), nullable=True),
    sa.Column('smtp_host', sa.String(length=255), nullable=True),
    sa.Column('smtp_port', sa.Integer(), nullable=True),
    sa.Column('smtp_username', sa.String(length=255), nullable=True),
    sa.Column('smtp_password', sa.Text(), nullable=True),
    sa.Column('enable_batch_sending', sa.Boolean(), nullable=True),
    sa.Column('batch_size', sa.Integer(), nullable=True),
    sa.Column('daily_limit', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('file_hashs',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('hash', sa.String(length=64), nullable=True),
    sa.Column('filename', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('reference_count', sa.BigInteger(), nullable=True),
    sa.Column('file_size', sa.BigInteger(), nullable=True),
    sa.Column('mime_type', sa.String(length=100), nullable=True),
    sa.Column('storage_path', sa.String(length=512), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('intel_briefings',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=500), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('briefing_type', sa.String(length=50), nullable=True),
    sa.Column('intelligence_ids', sa.Text(), nullable=True),
    sa.Column('channels_sent', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('intel_briefings', schema=None) as batch_op:
        batch_op.create_index('idx_intel_brief_type', ['briefing_type'], unique=False)

    op.create_table('intel_intelligence',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=500), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('sentiment', sa.String(length=20), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('importance_score', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('item_ids', sa.Text(), nullable=True),
    sa.Column('tags', sa.Text(), nullable=True),
    sa.Column('source_urls', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('intel_intelligence', schema=None) as batch_op:
        batch_op.create_index('idx_intel_intel_category', ['category'], unique=False)
        batch_op.create_index('idx_intel_intel_score', ['importance_score'], unique=False)
        batch_op.create_index('idx_intel_intel_sentiment', ['sentiment'], unique=False)

    op.create_table('login_attempts',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=255), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('is_success', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('login_attempts', schema=None) as batch_op:
        batch_op.create_index('idx_login_attempts_created', ['created_at'], unique=False)
        batch_op.create_index('idx_login_attempts_ip', ['ip_address'], unique=False)
        batch_op.create_index('idx_login_attempts_username', ['username'], unique=False)
        batch_op.create_index(batch_op.f('ix_login_attempts_ip_address'), ['ip_address'], unique=False)
        batch_op.create_index(batch_op.f('ix_login_attempts_username'), ['username'], unique=False)

    op.create_table('menus',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('slug', sa.String(length=100), nullable=True),
    sa.Column('location', sa.String(length=100), nullable=True),
    sa.Column('url', sa.String(length=500), nullable=True),
    sa.Column('target', sa.String(length=255), nullable=True),
    sa.Column('order_index', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('menus', schema=None) as batch_op:
        batch_op.create_index('idx_menus_is_active', ['is_active'], unique=False)
        batch_op.create_index('idx_menus_location', ['location'], unique=False)
        batch_op.create_index('idx_menus_order', ['order_index'], unique=False)
        batch_op.create_index('idx_menus_parent_id', ['parent_id'], unique=False)
        batch_op.create_index('idx_menus_slug', ['slug'], unique=True)

    op.create_table('page_builder',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('slug', sa.String(length=255), nullable=True),
    sa.Column('blocks_data', sa.Text(), nullable=False),
    sa.Column('template_name', sa.String(length=100), nullable=True),
    sa.Column('is_published', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    with op.batch_alter_table('page_builder', schema=None) as batch_op:
        batch_op.create_index('idx_page_builder_slug', ['slug'], unique=True)

    op.create_table('system_settings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('setting_key', sa.String(length=100), nullable=True),
    sa.Column('setting_value', sa.String(length=255), nullable=True),
    sa.Column('setting_type', sa.String(length=255), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('is_public', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('token_blacklist',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('token_identifier', sa.String(length=64), nullable=True),
    sa.Column('token_hash', sa.String(length=128), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('reason', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_identifier')
    )
    with op.batch_alter_table('token_blacklist', schema=None) as batch_op:
        batch_op.create_index('idx_token_blacklist_created', ['created_at'], unique=False)
        batch_op.create_index('idx_token_blacklist_expires', ['expires_at'], unique=False)

    op.create_table('upload_chunks',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('upload_id', sa.String(length=36), nullable=True),
    sa.Column('chunk_index', sa.BigInteger(), nullable=True),
    sa.Column('chunk_hash', sa.String(length=64), nullable=True),
    sa.Column('chunk_size', sa.BigInteger(), nullable=True),
    sa.Column('chunk_path', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('upload_tasks',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=True),
    sa.Column('filename', sa.String(length=255), nullable=True),
    sa.Column('total_size', sa.BigInteger(), nullable=True),
    sa.Column('total_chunks', sa.BigInteger(), nullable=True),
    sa.Column('uploaded_chunks', sa.BigInteger(), nullable=True),
    sa.Column('file_hash', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=255), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('password', sa.String(length=255), nullable=True),
    sa.Column('profile_picture', sa.String(length=255), nullable=True),
    sa.Column('bio', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_superuser', sa.Boolean(), nullable=True),
    sa.Column('date_joined', sa.DateTime(), nullable=True),
    sa.Column('last_login_at', sa.DateTime(), nullable=True),
    sa.Column('locale', sa.String(length=255), nullable=True),
    sa.Column('is_staff', sa.Boolean(), nullable=True),
    sa.Column('last_login_ip', sa.String(length=255), nullable=True),
    sa.Column('register_ip', sa.String(length=255), nullable=True),
    sa.Column('is_2fa_enabled', sa.Boolean(), nullable=True),
    sa.Column('totp_secret', sa.String(length=32), nullable=True),
    sa.Column('backup_codes', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index('idx_users_date_joined', ['date_joined'], unique=False)
        batch_op.create_index('idx_users_email', ['email'], unique=True)
        batch_op.create_index('idx_users_is_active', ['is_active'], unique=False)
        batch_op.create_index('idx_users_is_superuser', ['is_superuser'], unique=False)
        batch_op.create_index('idx_users_last_login', ['last_login_at'], unique=False)
        batch_op.create_index('idx_users_username', ['username'], unique=True)

    op.create_table('webhooks',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('url', sa.String(length=2048), nullable=True),
    sa.Column('secret', sa.String(length=255), nullable=True),
    sa.Column('events', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('webhooks', schema=None) as batch_op:
        batch_op.create_index('idx_webhooks_is_active', ['is_active'], unique=False)

    op.create_table('widget_instances',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('widget_type', sa.String(length=50), nullable=True),
    sa.Column('area', sa.String(length=50), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('config', sa.String(length=255), nullable=True),
    sa.Column('order_index', sa.BigInteger(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('conditions', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('widget_instances', schema=None) as batch_op:
        batch_op.create_index('idx_widget_instances_area', ['area'], unique=False)
        batch_op.create_index('idx_widget_instances_order', ['order_index'], unique=False)
        batch_op.create_index('idx_widget_instances_type', ['widget_type'], unique=False)

    op.create_table('workflow_agent_memories',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('agent_id', sa.String(length=100), nullable=True),
    sa.Column('session_id', sa.String(length=100), nullable=True),
    sa.Column('memory_type', sa.String(length=50), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('metadata_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('workflow_agent_memories', schema=None) as batch_op:
        batch_op.create_index('idx_mem_agent', ['agent_id'], unique=False)
        batch_op.create_index('idx_mem_session', ['session_id'], unique=False)
        batch_op.create_index('idx_mem_type', ['memory_type'], unique=False)

    op.create_table('workflow_agent_tools',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=200), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('tool_type', sa.String(length=50), nullable=True),
    sa.Column('schema', sa.Text(), nullable=True),
    sa.Column('config', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('workflow_agent_tools', schema=None) as batch_op:
        batch_op.create_index('idx_tool_type', ['tool_type'], unique=False)

    op.create_table('ai_workflows',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=True),
    sa.Column('task_type', sa.String(length=50), nullable=True),
    sa.Column('input_data', sa.Text(), nullable=False),
    sa.Column('output_data', sa.Text(), nullable=True),
    sa.Column('model_used', sa.String(length=100), nullable=True),
    sa.Column('tokens_used', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ai_workflows', schema=None) as batch_op:
        batch_op.create_index('idx_ai_workflows_status', ['status'], unique=False)
        batch_op.create_index('idx_ai_workflows_task_type', ['task_type'], unique=False)
        batch_op.create_index('idx_ai_workflows_user_id', ['user_id'], unique=False)

    op.create_table('approval_records',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('content_type', sa.String(length=50), nullable=False),
    sa.Column('content_id', sa.BigInteger(), nullable=False),
    sa.Column('applicant_id', sa.BigInteger(), nullable=False),
    sa.Column('current_level', sa.Integer(), nullable=False),
    sa.Column('max_level', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['applicant_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('approval_records', schema=None) as batch_op:
        batch_op.create_index('idx_approval_records_applicant_id', ['applicant_id'], unique=False)
        batch_op.create_index('idx_approval_records_content', ['content_type', 'content_id'], unique=False)
        batch_op.create_index('idx_approval_records_created_at', ['created_at'], unique=False)
        batch_op.create_index('idx_approval_records_status', ['status'], unique=False)

    op.create_table('articles',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('slug', sa.String(length=255), nullable=True),
    sa.Column('excerpt', sa.String(length=255), nullable=True),
    sa.Column('cover_image', sa.String(length=255), nullable=True),
    sa.Column('category', sa.BigInteger(), nullable=True),
    sa.Column('tags_list', sa.String(length=255), nullable=True),
    sa.Column('views', sa.BigInteger(), nullable=True),
    sa.Column('user', sa.BigInteger(), nullable=True),
    sa.Column('status', sa.Integer(), nullable=True),
    sa.Column('hidden', sa.Boolean(), nullable=True),
    sa.Column('is_featured', sa.Boolean(), nullable=True),
    sa.Column('is_vip_only', sa.Boolean(), nullable=True),
    sa.Column('required_vip_level', sa.Integer(), nullable=True),
    sa.Column('article_ad', sa.String(length=255), nullable=True),
    sa.Column('scheduled_publish_at', sa.DateTime(), nullable=True),
    sa.Column('post_type', sa.String(length=50), nullable=True),
    sa.Column('is_sticky', sa.Boolean(), nullable=True),
    sa.Column('sticky_until', sa.DateTime(), nullable=True),
    sa.Column('sort_order', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('seo_title', sa.String(length=255), nullable=True),
    sa.Column('seo_description', sa.Text(), nullable=True),
    sa.Column('seo_keywords', sa.String(length=500), nullable=True),
    sa.Column('og_title', sa.String(length=255), nullable=True),
    sa.Column('og_description', sa.Text(), nullable=True),
    sa.Column('og_image', sa.String(length=500), nullable=True),
    sa.Column('og_type', sa.String(length=50), nullable=True),
    sa.Column('twitter_title', sa.String(length=255), nullable=True),
    sa.Column('twitter_description', sa.Text(), nullable=True),
    sa.Column('twitter_image', sa.String(length=500), nullable=True),
    sa.Column('twitter_card', sa.String(length=50), nullable=True),
    sa.Column('canonical_url', sa.String(length=500), nullable=True),
    sa.Column('robots_meta', sa.String(length=100), nullable=True),
    sa.Column('schema_org_enabled', sa.Boolean(), nullable=True),
    sa.Column('schema_org_type', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['category'], ['categories.id'], ),
    sa.ForeignKeyConstraint(['user'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('articles', schema=None) as batch_op:
        batch_op.create_index('idx_articles_category_status_created', ['category', 'status', 'created_at'], unique=False)
        batch_op.create_index('idx_articles_slug', ['slug'], unique=True)
        batch_op.create_index('idx_articles_status_created', ['status', 'created_at'], unique=False)
        batch_op.create_index('idx_articles_user_status_created', ['user', 'status', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_articles_post_type'), ['post_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_articles_sort_order'), ['sort_order'], unique=False)

    op.create_table('audit_logs',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=True),
    sa.Column('resource_type', sa.String(length=50), nullable=True),
    sa.Column('resource_id', sa.BigInteger(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.create_index('idx_audit_logs_action', ['action'], unique=False)
        batch_op.create_index('idx_audit_logs_created_at', ['created_at'], unique=False)
        batch_op.create_index('idx_audit_logs_resource', ['resource_type', 'resource_id'], unique=False)
        batch_op.create_index('idx_audit_logs_user_id', ['user_id'], unique=False)

    op.create_table('block_patterns',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('blocks', sa.Text(), nullable=False),
    sa.Column('keywords', sa.Text(), nullable=True),
    sa.Column('thumbnail', sa.String(length=500), nullable=True),
    sa.Column('is_public', sa.Boolean(), nullable=True),
    sa.Column('user_id', sa.BigInteger(), nullable=True),
    sa.Column('viewport_width', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    with op.batch_alter_table('block_patterns', schema=None) as batch_op:
        batch_op.create_index('idx_block_patterns_category', ['category'], unique=False)
        batch_op.create_index('idx_block_patterns_name', ['name'], unique=True)
        batch_op.create_index('idx_block_patterns_user_id', ['user_id'], unique=False)

    op.create_table('intel_alert_rules',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=200), nullable=True),
    sa.Column('conditions', sa.Text(), nullable=True),
    sa.Column('keywords', sa.Text(), nullable=True),
    sa.Column('severity', sa.String(length=20), nullable=True),
    sa.Column('actions', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_by', sa.BigInteger(), nullable=True),
    sa.Column('last_triggered_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('intel_alert_rules', schema=None) as batch_op:
        batch_op.create_index('idx_intel_ar_active', ['is_active'], unique=False)
        batch_op.create_index('idx_intel_ar_severity', ['severity'], unique=False)

    op.create_table('intel_data_sources',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=200), nullable=True),
    sa.Column('source_type', sa.String(length=50), nullable=True),
    sa.Column('url', sa.Text(), nullable=True),
    sa.Column('config', sa.Text(), nullable=True),
    sa.Column('schedule_cron', sa.String(length=100), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('last_collected_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('intel_data_sources', schema=None) as batch_op:
        batch_op.create_index('idx_intel_ds_active', ['is_active'], unique=False)
        batch_op.create_index('idx_intel_ds_type', ['source_type'], unique=False)

    op.create_table('knowledge_bases',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=200), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('embedding_model', sa.String(length=100), nullable=True),
    sa.Column('chunk_size', sa.Integer(), nullable=True),
    sa.Column('chunk_overlap', sa.Integer(), nullable=True),
    sa.Column('vector_collection', sa.String(length=100), nullable=True),
    sa.Column('document_count', sa.Integer(), nullable=True),
    sa.Column('chunk_count', sa.Integer(), nullable=True),
    sa.Column('created_by', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('knowledge_bases', schema=None) as batch_op:
        batch_op.create_index('idx_kb_name', ['name'], unique=False)

    op.create_table('knowledge_report_templates',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=200), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('template_content', sa.Text(), nullable=True),
    sa.Column('sections', sa.Text(), nullable=True),
    sa.Column('created_by', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('media_folders',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('parent_id', sa.BigInteger(), nullable=True),
    sa.Column('user', sa.BigInteger(), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('sort_order', sa.BigInteger(), nullable=True),
    sa.Column('is_public', sa.Boolean(), nullable=True),
    sa.Column('media_count', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['media_folders.id'], ),
    sa.ForeignKeyConstraint(['user'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('media_folders', schema=None) as batch_op:
        batch_op.create_index('idx_media_folders_parent_id', ['parent_id'], unique=False)
        batch_op.create_index('idx_media_folders_unique_name', ['user', 'parent_id', 'name'], unique=True)
        batch_op.create_index('idx_media_folders_user_id', ['user'], unique=False)

    op.create_table('notifications',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('recipient', sa.BigInteger(), nullable=True),
    sa.Column('type', sa.String(length=100), nullable=True),
    sa.Column('title', sa.String(length=200), nullable=True),
    sa.Column('message', sa.String(length=255), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=True),
    sa.Column('read_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['recipient'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('oauth_accounts',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=True),
    sa.Column('provider', sa.String(length=50), nullable=True),
    sa.Column('provider_user_id', sa.String(length=255), nullable=True),
    sa.Column('access_token', sa.String(length=255), nullable=True),
    sa.Column('refresh_token', sa.String(length=255), nullable=True),
    sa.Column('token_expires_at', sa.DateTime(), nullable=True),
    sa.Column('extra_data', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('oauth_accounts', schema=None) as batch_op:
        batch_op.create_index('idx_oauth_accounts_provider_user', ['provider', 'provider_user_id'], unique=True)
        batch_op.create_index('idx_oauth_accounts_user_provider', ['user_id', 'provider'], unique=True)
        batch_op.create_index(batch_op.f('ix_oauth_accounts_provider'), ['provider'], unique=False)
        batch_op.create_index(batch_op.f('ix_oauth_accounts_provider_user_id'), ['provider_user_id'], unique=False)

    op.create_table('search_history',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user', sa.BigInteger(), nullable=True),
    sa.Column('keyword', sa.String(length=255), nullable=True),
    sa.Column('results_count', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('search_history', schema=None) as batch_op:
        batch_op.create_index('idx_search_history_created', ['created_at'], unique=False)
        batch_op.create_index('idx_search_history_keyword', ['keyword'], unique=False)
        batch_op.create_index('idx_search_history_user', ['user'], unique=False)

    op.create_table('user_sessions',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=True),
    sa.Column('access_token', sa.String(length=255), nullable=True),
    sa.Column('refresh_token', sa.String(length=255), nullable=True),
    sa.Column('device_info', sa.String(length=500), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('location', sa.String(length=100), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('last_activity', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('access_token')
    )
    with op.batch_alter_table('user_sessions', schema=None) as batch_op:
        batch_op.create_index('idx_user_access_token', ['access_token'], unique=True)
        batch_op.create_index('idx_user_sessions_expires', ['expires_at'], unique=False)
        batch_op.create_index('idx_user_sessions_is_active', ['is_active'], unique=False)
        batch_op.create_index('idx_user_sessions_user_id', ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_sessions_refresh_token'), ['refresh_token'], unique=False)

    op.create_table('webhook_deliveries',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('webhook', sa.BigInteger(), nullable=True),
    sa.Column('event', sa.String(length=100), nullable=True),
    sa.Column('payload', sa.Text(), nullable=False),
    sa.Column('response_status', sa.Integer(), nullable=True),
    sa.Column('response_body', sa.Text(), nullable=True),
    sa.Column('success', sa.Boolean(), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=True),
    sa.Column('next_retry_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['webhook'], ['webhooks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('webhook_deliveries', schema=None) as batch_op:
        batch_op.create_index('idx_webhook_deliveries_created', ['created_at'], unique=False)
        batch_op.create_index('idx_webhook_deliveries_event', ['event'], unique=False)
        batch_op.create_index('idx_webhook_deliveries_success', ['success'], unique=False)
        batch_op.create_index('idx_webhook_deliveries_webhook', ['webhook'], unique=False)

    op.create_table('workflow_definitions',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=200), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=True),
    sa.Column('graph', sa.Text(), nullable=True),
    sa.Column('trigger_config', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_by', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('workflow_definitions', schema=None) as batch_op:
        batch_op.create_index('idx_wfd_active', ['is_active'], unique=False)

    op.create_table('approval_steps',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('record_id', sa.BigInteger(), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('approver_id', sa.BigInteger(), nullable=False),
    sa.Column('action', sa.String(length=20), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['approver_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['record_id'], ['approval_records.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('approval_steps', schema=None) as batch_op:
        batch_op.create_index('idx_approval_steps_approver_id', ['approver_id'], unique=False)
        batch_op.create_index('idx_approval_steps_record_id', ['record_id'], unique=False)
        batch_op.create_index('idx_approval_steps_record_level', ['record_id', 'level'], unique=False)

    op.create_table('article_annotations',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('article', sa.BigInteger(), nullable=True),
    sa.Column('user', sa.BigInteger(), nullable=True),
    sa.Column('parent', sa.BigInteger(), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('position', sa.Text(), nullable=True),
    sa.Column('selection_text', sa.String(length=500), nullable=True),
    sa.Column('is_resolved', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['article'], ['articles.id'], ),
    sa.ForeignKeyConstraint(['parent'], ['article_annotations.id'], ),
    sa.ForeignKeyConstraint(['user'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('article_annotations', schema=None) as batch_op:
        batch_op.create_index('idx_article_annotations_article', ['article'], unique=False)
        batch_op.create_index('idx_article_annotations_parent', ['parent'], unique=False)
        batch_op.create_index('idx_article_annotations_resolved', ['is_resolved'], unique=False)
        batch_op.create_index('idx_article_annotations_user', ['user'], unique=False)

    op.create_table('article_content',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('article', sa.BigInteger(), nullable=True),
    sa.Column('passwd', sa.String(length=255), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('language_code', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['article'], ['articles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('article_revisions',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('article_id', sa.BigInteger(), nullable=True),
    sa.Column('revision_number', sa.BigInteger(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('excerpt', sa.String(length=255), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('cover_image', sa.String(length=255), nullable=True),
    sa.Column('tags_list', sa.String(length=255), nullable=True),
    sa.Column('category_id', sa.BigInteger(), nullable=True),
    sa.Column('status', sa.BigInteger(), nullable=True),
    sa.Column('hidden', sa.Boolean(), nullable=True),
    sa.Column('is_featured', sa.Boolean(), nullable=True),
    sa.Column('is_vip_only', sa.Boolean(), nullable=True),
    sa.Column('required_vip_level', sa.BigInteger(), nullable=True),
    sa.Column('author_id', sa.BigInteger(), nullable=True),
    sa.Column('change_summary', sa.String(length=500), nullable=True),
    sa.Column('hash_code', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['article_id'], ['articles.id'], ),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('article_revisions', schema=None) as batch_op:
        batch_op.create_index('idx_article_revisions_article_id', ['article_id'], unique=False)
        batch_op.create_index('idx_article_revisions_created', ['created_at'], unique=False)
        batch_op.create_index('idx_article_revisions_hash', ['hash_code'], unique=False)
        batch_op.create_index('idx_article_revisions_number', ['revision_number'], unique=False)
        batch_op.create_index(batch_op.f('ix_article_revisions_hash_code'), ['hash_code'], unique=False)

    op.create_table('intel_alert_events',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('rule_id', sa.BigInteger(), nullable=True),
    sa.Column('intelligence_id', sa.BigInteger(), nullable=True),
    sa.Column('severity', sa.String(length=20), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['intelligence_id'], ['intel_intelligence.id'], ),
    sa.ForeignKeyConstraint(['rule_id'], ['intel_alert_rules.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('intel_alert_events', schema=None) as batch_op:
        batch_op.create_index('idx_intel_ae_rule', ['rule_id'], unique=False)
        batch_op.create_index('idx_intel_ae_status', ['status'], unique=False)

    op.create_table('intel_collected_items',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('source_id', sa.BigInteger(), nullable=True),
    sa.Column('url', sa.Text(), nullable=True),
    sa.Column('title', sa.String(length=500), nullable=True),
    sa.Column('content_raw', sa.Text(), nullable=True),
    sa.Column('content_cleaned', sa.Text(), nullable=True),
    sa.Column('content_hash', sa.String(length=64), nullable=True),
    sa.Column('metadata_json', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('collected_at', sa.DateTime(), nullable=True),
    sa.Column('analyzed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['source_id'], ['intel_data_sources.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('intel_collected_items', schema=None) as batch_op:
        batch_op.create_index('idx_intel_ci_hash', ['content_hash'], unique=False)
        batch_op.create_index('idx_intel_ci_source', ['source_id'], unique=False)
        batch_op.create_index('idx_intel_ci_status', ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_intel_collected_items_content_hash'), ['content_hash'], unique=False)

    op.create_table('knowledge_documents',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('knowledge_base_id', sa.BigInteger(), nullable=True),
    sa.Column('title', sa.String(length=500), nullable=True),
    sa.Column('file_path', sa.Text(), nullable=True),
    sa.Column('file_type', sa.String(length=50), nullable=True),
    sa.Column('content_text', sa.Text(), nullable=True),
    sa.Column('chunk_count', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('metadata_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['knowledge_base_id'], ['knowledge_bases.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('knowledge_documents', schema=None) as batch_op:
        batch_op.create_index('idx_kd_kb', ['knowledge_base_id'], unique=False)
        batch_op.create_index('idx_kd_status', ['status'], unique=False)

    op.create_table('knowledge_generated_reports',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('template_id', sa.BigInteger(), nullable=True),
    sa.Column('title', sa.String(length=500), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('knowledge_base_ids', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('created_by', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['template_id'], ['knowledge_report_templates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('knowledge_generated_reports', schema=None) as batch_op:
        batch_op.create_index('idx_gr_status', ['status'], unique=False)
        batch_op.create_index('idx_gr_template', ['template_id'], unique=False)

    op.create_table('media',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user', sa.BigInteger(), nullable=True),
    sa.Column('hash', sa.String(length=64), nullable=True),
    sa.Column('filename', sa.String(length=255), nullable=True),
    sa.Column('original_filename', sa.String(length=255), nullable=True),
    sa.Column('file_path', sa.String(length=500), nullable=True),
    sa.Column('file_url', sa.String(length=500), nullable=True),
    sa.Column('file_size', sa.BigInteger(), nullable=True),
    sa.Column('file_type', sa.String(length=255), nullable=True),
    sa.Column('mime_type', sa.String(length=255), nullable=True),
    sa.Column('width', sa.BigInteger(), nullable=True),
    sa.Column('height', sa.BigInteger(), nullable=True),
    sa.Column('duration', sa.BigInteger(), nullable=True),
    sa.Column('thumbnail_path', sa.String(length=255), nullable=True),
    sa.Column('thumbnail_url', sa.String(length=255), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('alt_text', sa.String(length=255), nullable=True),
    sa.Column('is_public', sa.Boolean(), nullable=True),
    sa.Column('download_count', sa.BigInteger(), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('tags', sa.String(length=500), nullable=True),
    sa.Column('folder_id', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['folder_id'], ['media_folders.id'], ),
    sa.ForeignKeyConstraint(['user'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('media', schema=None) as batch_op:
        batch_op.create_index('idx_media_created_at', ['created_at'], unique=False)
        batch_op.create_index('idx_media_file_type', ['file_type'], unique=False)
        batch_op.create_index('idx_media_folder', ['folder_id'], unique=False)
        batch_op.create_index('idx_media_hash', ['hash'], unique=True)
        batch_op.create_index('idx_media_is_public', ['is_public'], unique=False)
        batch_op.create_index('idx_media_user', ['user'], unique=False)

    op.create_table('workflow_executions',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('workflow_id', sa.BigInteger(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('trigger_type', sa.String(length=50), nullable=True),
    sa.Column('input_data', sa.Text(), nullable=True),
    sa.Column('output_data', sa.Text(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['workflow_id'], ['workflow_definitions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('workflow_executions', schema=None) as batch_op:
        batch_op.create_index('idx_wfe_status', ['status'], unique=False)
        batch_op.create_index('idx_wfe_workflow', ['workflow_id'], unique=False)

    op.create_table('workflow_triggers',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('workflow_id', sa.BigInteger(), nullable=True),
    sa.Column('trigger_type', sa.String(length=50), nullable=True),
    sa.Column('config', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('last_fired_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['workflow_id'], ['workflow_definitions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('workflow_triggers', schema=None) as batch_op:
        batch_op.create_index('idx_trigger_workflow', ['workflow_id'], unique=False)

    op.create_table('download_tasks',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=True),
    sa.Column('source_url', sa.String(length=2048), nullable=True),
    sa.Column('resource_type', sa.String(length=50), nullable=True),
    sa.Column('filename', sa.String(length=255), nullable=True),
    sa.Column('total_size', sa.BigInteger(), nullable=True),
    sa.Column('downloaded_size', sa.BigInteger(), nullable=True),
    sa.Column('progress', sa.Integer(), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('media_id', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['media_id'], ['media.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('download_tasks', schema=None) as batch_op:
        batch_op.create_index('idx_download_tasks_created', ['created_at'], unique=False)
        batch_op.create_index('idx_download_tasks_priority', ['priority', 'created_at'], unique=False)
        batch_op.create_index('idx_download_tasks_status', ['status'], unique=False)
        batch_op.create_index('idx_download_tasks_user', ['user_id'], unique=False)

    op.create_table('knowledge_document_chunks',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('document_id', sa.BigInteger(), nullable=True),
    sa.Column('knowledge_base_id', sa.BigInteger(), nullable=True),
    sa.Column('chunk_index', sa.Integer(), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('embedding_id', sa.String(length=100), nullable=True),
    sa.Column('metadata_json', sa.Text(), nullable=True),
    sa.Column('token_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['knowledge_documents.id'], ),
    sa.ForeignKeyConstraint(['knowledge_base_id'], ['knowledge_bases.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('knowledge_document_chunks', schema=None) as batch_op:
        batch_op.create_index('idx_dc_doc', ['document_id'], unique=False)
        batch_op.create_index('idx_dc_kb', ['knowledge_base_id'], unique=False)

    op.create_table('workflow_node_executions',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('execution_id', sa.BigInteger(), nullable=True),
    sa.Column('node_id', sa.String(length=100), nullable=True),
    sa.Column('node_type', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('input_data', sa.Text(), nullable=True),
    sa.Column('output_data', sa.Text(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['execution_id'], ['workflow_executions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('workflow_node_executions', schema=None) as batch_op:
        batch_op.create_index('idx_ne_execution', ['execution_id'], unique=False)
        batch_op.create_index('idx_ne_status', ['status'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workflow_node_executions', schema=None) as batch_op:
        batch_op.drop_index('idx_ne_status')
        batch_op.drop_index('idx_ne_execution')

    op.drop_table('workflow_node_executions')
    with op.batch_alter_table('knowledge_document_chunks', schema=None) as batch_op:
        batch_op.drop_index('idx_dc_kb')
        batch_op.drop_index('idx_dc_doc')

    op.drop_table('knowledge_document_chunks')
    with op.batch_alter_table('download_tasks', schema=None) as batch_op:
        batch_op.drop_index('idx_download_tasks_user')
        batch_op.drop_index('idx_download_tasks_status')
        batch_op.drop_index('idx_download_tasks_priority')
        batch_op.drop_index('idx_download_tasks_created')

    op.drop_table('download_tasks')
    with op.batch_alter_table('workflow_triggers', schema=None) as batch_op:
        batch_op.drop_index('idx_trigger_workflow')

    op.drop_table('workflow_triggers')
    with op.batch_alter_table('workflow_executions', schema=None) as batch_op:
        batch_op.drop_index('idx_wfe_workflow')
        batch_op.drop_index('idx_wfe_status')

    op.drop_table('workflow_executions')
    with op.batch_alter_table('media', schema=None) as batch_op:
        batch_op.drop_index('idx_media_user')
        batch_op.drop_index('idx_media_is_public')
        batch_op.drop_index('idx_media_hash')
        batch_op.drop_index('idx_media_folder')
        batch_op.drop_index('idx_media_file_type')
        batch_op.drop_index('idx_media_created_at')

    op.drop_table('media')
    with op.batch_alter_table('knowledge_generated_reports', schema=None) as batch_op:
        batch_op.drop_index('idx_gr_template')
        batch_op.drop_index('idx_gr_status')

    op.drop_table('knowledge_generated_reports')
    with op.batch_alter_table('knowledge_documents', schema=None) as batch_op:
        batch_op.drop_index('idx_kd_status')
        batch_op.drop_index('idx_kd_kb')

    op.drop_table('knowledge_documents')
    with op.batch_alter_table('intel_collected_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_intel_collected_items_content_hash'))
        batch_op.drop_index('idx_intel_ci_status')
        batch_op.drop_index('idx_intel_ci_source')
        batch_op.drop_index('idx_intel_ci_hash')

    op.drop_table('intel_collected_items')
    with op.batch_alter_table('intel_alert_events', schema=None) as batch_op:
        batch_op.drop_index('idx_intel_ae_status')
        batch_op.drop_index('idx_intel_ae_rule')

    op.drop_table('intel_alert_events')
    with op.batch_alter_table('article_revisions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_article_revisions_hash_code'))
        batch_op.drop_index('idx_article_revisions_number')
        batch_op.drop_index('idx_article_revisions_hash')
        batch_op.drop_index('idx_article_revisions_created')
        batch_op.drop_index('idx_article_revisions_article_id')

    op.drop_table('article_revisions')
    op.drop_table('article_content')
    with op.batch_alter_table('article_annotations', schema=None) as batch_op:
        batch_op.drop_index('idx_article_annotations_user')
        batch_op.drop_index('idx_article_annotations_resolved')
        batch_op.drop_index('idx_article_annotations_parent')
        batch_op.drop_index('idx_article_annotations_article')

    op.drop_table('article_annotations')
    with op.batch_alter_table('approval_steps', schema=None) as batch_op:
        batch_op.drop_index('idx_approval_steps_record_level')
        batch_op.drop_index('idx_approval_steps_record_id')
        batch_op.drop_index('idx_approval_steps_approver_id')

    op.drop_table('approval_steps')
    with op.batch_alter_table('workflow_definitions', schema=None) as batch_op:
        batch_op.drop_index('idx_wfd_active')

    op.drop_table('workflow_definitions')
    with op.batch_alter_table('webhook_deliveries', schema=None) as batch_op:
        batch_op.drop_index('idx_webhook_deliveries_webhook')
        batch_op.drop_index('idx_webhook_deliveries_success')
        batch_op.drop_index('idx_webhook_deliveries_event')
        batch_op.drop_index('idx_webhook_deliveries_created')

    op.drop_table('webhook_deliveries')
    with op.batch_alter_table('user_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_sessions_refresh_token'))
        batch_op.drop_index('idx_user_sessions_user_id')
        batch_op.drop_index('idx_user_sessions_is_active')
        batch_op.drop_index('idx_user_sessions_expires')
        batch_op.drop_index('idx_user_access_token')

    op.drop_table('user_sessions')
    with op.batch_alter_table('search_history', schema=None) as batch_op:
        batch_op.drop_index('idx_search_history_user')
        batch_op.drop_index('idx_search_history_keyword')
        batch_op.drop_index('idx_search_history_created')

    op.drop_table('search_history')
    with op.batch_alter_table('oauth_accounts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_oauth_accounts_provider_user_id'))
        batch_op.drop_index(batch_op.f('ix_oauth_accounts_provider'))
        batch_op.drop_index('idx_oauth_accounts_user_provider')
        batch_op.drop_index('idx_oauth_accounts_provider_user')

    op.drop_table('oauth_accounts')
    op.drop_table('notifications')
    with op.batch_alter_table('media_folders', schema=None) as batch_op:
        batch_op.drop_index('idx_media_folders_user_id')
        batch_op.drop_index('idx_media_folders_unique_name')
        batch_op.drop_index('idx_media_folders_parent_id')

    op.drop_table('media_folders')
    op.drop_table('knowledge_report_templates')
    with op.batch_alter_table('knowledge_bases', schema=None) as batch_op:
        batch_op.drop_index('idx_kb_name')

    op.drop_table('knowledge_bases')
    with op.batch_alter_table('intel_data_sources', schema=None) as batch_op:
        batch_op.drop_index('idx_intel_ds_type')
        batch_op.drop_index('idx_intel_ds_active')

    op.drop_table('intel_data_sources')
    with op.batch_alter_table('intel_alert_rules', schema=None) as batch_op:
        batch_op.drop_index('idx_intel_ar_severity')
        batch_op.drop_index('idx_intel_ar_active')

    op.drop_table('intel_alert_rules')
    with op.batch_alter_table('block_patterns', schema=None) as batch_op:
        batch_op.drop_index('idx_block_patterns_user_id')
        batch_op.drop_index('idx_block_patterns_name')
        batch_op.drop_index('idx_block_patterns_category')

    op.drop_table('block_patterns')
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_index('idx_audit_logs_user_id')
        batch_op.drop_index('idx_audit_logs_resource')
        batch_op.drop_index('idx_audit_logs_created_at')
        batch_op.drop_index('idx_audit_logs_action')

    op.drop_table('audit_logs')
    with op.batch_alter_table('articles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_articles_sort_order'))
        batch_op.drop_index(batch_op.f('ix_articles_post_type'))
        batch_op.drop_index('idx_articles_user_status_created')
        batch_op.drop_index('idx_articles_status_created')
        batch_op.drop_index('idx_articles_slug')
        batch_op.drop_index('idx_articles_category_status_created')

    op.drop_table('articles')
    with op.batch_alter_table('approval_records', schema=None) as batch_op:
        batch_op.drop_index('idx_approval_records_status')
        batch_op.drop_index('idx_approval_records_created_at')
        batch_op.drop_index('idx_approval_records_content')
        batch_op.drop_index('idx_approval_records_applicant_id')

    op.drop_table('approval_records')
    with op.batch_alter_table('ai_workflows', schema=None) as batch_op:
        batch_op.drop_index('idx_ai_workflows_user_id')
        batch_op.drop_index('idx_ai_workflows_task_type')
        batch_op.drop_index('idx_ai_workflows_status')

    op.drop_table('ai_workflows')
    with op.batch_alter_table('workflow_agent_tools', schema=None) as batch_op:
        batch_op.drop_index('idx_tool_type')

    op.drop_table('workflow_agent_tools')
    with op.batch_alter_table('workflow_agent_memories', schema=None) as batch_op:
        batch_op.drop_index('idx_mem_type')
        batch_op.drop_index('idx_mem_session')
        batch_op.drop_index('idx_mem_agent')

    op.drop_table('workflow_agent_memories')
    with op.batch_alter_table('widget_instances', schema=None) as batch_op:
        batch_op.drop_index('idx_widget_instances_type')
        batch_op.drop_index('idx_widget_instances_order')
        batch_op.drop_index('idx_widget_instances_area')

    op.drop_table('widget_instances')
    with op.batch_alter_table('webhooks', schema=None) as batch_op:
        batch_op.drop_index('idx_webhooks_is_active')

    op.drop_table('webhooks')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index('idx_users_username')
        batch_op.drop_index('idx_users_last_login')
        batch_op.drop_index('idx_users_is_superuser')
        batch_op.drop_index('idx_users_is_active')
        batch_op.drop_index('idx_users_email')
        batch_op.drop_index('idx_users_date_joined')

    op.drop_table('users')
    op.drop_table('upload_tasks')
    op.drop_table('upload_chunks')
    with op.batch_alter_table('token_blacklist', schema=None) as batch_op:
        batch_op.drop_index('idx_token_blacklist_expires')
        batch_op.drop_index('idx_token_blacklist_created')

    op.drop_table('token_blacklist')
    op.drop_table('system_settings')
    with op.batch_alter_table('page_builder', schema=None) as batch_op:
        batch_op.drop_index('idx_page_builder_slug')

    op.drop_table('page_builder')
    with op.batch_alter_table('menus', schema=None) as batch_op:
        batch_op.drop_index('idx_menus_slug')
        batch_op.drop_index('idx_menus_parent_id')
        batch_op.drop_index('idx_menus_order')
        batch_op.drop_index('idx_menus_location')
        batch_op.drop_index('idx_menus_is_active')

    op.drop_table('menus')
    with op.batch_alter_table('login_attempts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_login_attempts_username'))
        batch_op.drop_index(batch_op.f('ix_login_attempts_ip_address'))
        batch_op.drop_index('idx_login_attempts_username')
        batch_op.drop_index('idx_login_attempts_ip')
        batch_op.drop_index('idx_login_attempts_created')

    op.drop_table('login_attempts')
    with op.batch_alter_table('intel_intelligence', schema=None) as batch_op:
        batch_op.drop_index('idx_intel_intel_sentiment')
        batch_op.drop_index('idx_intel_intel_score')
        batch_op.drop_index('idx_intel_intel_category')

    op.drop_table('intel_intelligence')
    with op.batch_alter_table('intel_briefings', schema=None) as batch_op:
        batch_op.drop_index('idx_intel_brief_type')

    op.drop_table('intel_briefings')
    op.drop_table('file_hashs')
    op.drop_table('email_service_configs')
    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.drop_index('idx_categories_sort_order')
        batch_op.drop_index('idx_categories_slug')
        batch_op.drop_index('idx_categories_parent')
        batch_op.drop_index('idx_categories_is_visible')

    op.drop_table('categories')
    # ### end Alembic commands ###
